exclude: "^docs/|/migrations/"
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: no-commit-to-branch
        stages: [pre-push, pre-merge-commit]
        args: ["-p", "main", "-p", "master", "-p", "releases"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        # args: ["--config=setup.cfg"]
        args: ["--ignore=E501", "--exclude=*.py"]
        additional_dependencies: [flake8-isort]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "8cd2d4056637e242709fe09f15a36f0b4b682bda"
    hooks:
      - id: mypy
        additional_dependencies:
          [
            numpy>=1.26.3,
            mypy-protobuf>=3.5.0,
            grpc-stubs>=1.53.0.5,
            watchfiles>=0.21.0,
            redis>=5.0.1,
          ]

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
