version: "3.8"

name: "pathfinder-local"

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: pathfinder
    stdin_open: true
    command: "/start"
    volumes:
      - ./src:/app:z
    env_file:
      - ./.envs/.local/.app
    ports:
      - 50051:50051

  monitor:
    build:
      context: .
      dockerfile: ./compose/monitoring/Dockerfile
    image: monitor
    stdin_open: true
    env_file:
      - ./.envs/.local/.app

    ports:
      - 50052:8501

    profiles:
      - "mon"

  redis:
    image: redis:7
