version: "3.8"

name: "pathfinder"
volumes:
  - redis-data: {}

services:
  app:
    image: ghcr.io/sbkubric/ars-pathfinder:latest
    restart: always
    env_file:
      - ./.envs/.production/.app
    command: /start
  ports:
    - 50051:50051

  redis:
    image: redis:7
    command: redis-server --save 60 10
    volumes:
      - redis-data:/data
