name: "CI: Pathfinder"

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

  release:
    types: [published]

  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements/local.txt

      - name: pre-commit
        run: |
          python3.11 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements/local.txt
          pip install -r requirements/production.txt
          pre-commit run --show-diff-on-failure --color=always --all-files

  pytest:
    runs-on: ubuntu-latest
    needs:
      - linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/local.txt

      - name: pytest
        run: |
          python3.11 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements/local.txt
          mkdir src/server/lib
          python -m grpc_tools.protoc -I . --python_out=./src/server/lib/ --grpc_python_out=./src/server/lib/ ./pathfinder.proto --mypy_out=./src/server/lib/ --grpclib_python_out=./src/server/lib/
          pytest .

  builder:
    environment: production
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    needs:
      - pytest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/local.txt

      - name: Set tag to output
        id: vars
        run: echo "tag=${GITHUB_REF#release/*/}" >> $GITHUB_OUTPUT

      - name: Build proto files
        run: |
          python3.11 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements/local.txt
          mkdir src/server/lib
          python -m grpc_tools.protoc -I . --python_out=./src/server/lib/ --grpc_python_out=./src/server/lib/ ./pathfinder.proto --mypy_out=./src/server/lib/ --grpclib_python_out=./src/server/lib/

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          file: "./compose/production/Dockerfile"
          push: ${{ github.event_name == 'release' }}
          tags: |
            ghcr.io/sbkubric/ars-pathfinder:latest
            ghcr.io/sbkubric/ars-pathfinder:${{ steps.vars.outputs.tag }}

          labels: |
            maintainer=${{ github.actor }}
            build-date=${{ github.event.head_commit.timestamp }}
